GPU_ID: 1
SOURCE: GTA
TARGET: Cityscapes
NUM_WORKERS: 4
TRAIN:
  DA_METHOD: hcl_source
  MODEL: DeepLabv2
  RESTORE_FROM: ./pretrained_models/DeepLab_resnet_pretrained_imagenet.pth
  MULTI_LEVEL: True
  LAMBDA_ENT_MAIN: 0.001
  LAMBDA_ENT_AUX: 0.0002
  SAVE_PRED_EVERY: 100
TEST:
  MODE: best
  SNAPSHOT_STEP: 2000
